title: 2018 Goober Bowl
author: David Killy
email: davekilly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  THIS SITE IS UNDER CONSTRUCTION!

twitter_username: macrod68
github_username:  davekilly

sass:
    style: compressed
